name: Build CI

on:
  push:
    branches: [ main ]
    paths:
      - 'wallguard-server/**'
      - 'wallguard-common/**'
      - 'wallguard/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'wallguard-server/**'
      - 'wallguard-common/**'
      - 'wallguard/**'

jobs:
  build-linux:
    name: Build & Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libpcap-dev protobuf-compiler libpipewire-0.3-dev \
            libpipewire-0.3-modules libspa-0.2-dev libxcb1-dev libxcb-shm0-dev \
            libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build workspace
        run: cargo build --verbose

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test -- --nocapture

  build-windows:
    name: Build & Test (Windows)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          choco install -y protoc

          Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.13.zip" -OutFile "C:/npcap-sdk.zip"
          Expand-Archive -LiteralPath C:/npcap-sdk.zip -DestinationPath C:/npcap-sdk
          echo "LIB=C:/npcap-sdk/Lib/x64" >> $env:GITHUB_ENV

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build workspace
        run: cargo build --verbose

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test -- --nocapture


  build-bsd:
    name: Build & Test (${{ matrix.platform.name }})
    runs-on: ubuntu-latest
    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: FreeBSD, os: freebsd, os-version: '14.3', arch: x86_64 }

    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive

    - name: Install Dependencies
      uses: cross-platform-actions/action@v0.30.0
      with:
        operating_system: ${{ matrix.platform.os }}
        architecture: ${{ matrix.platform.arch }}
        version: ${{ matrix.platform.os-version }}
        cpu_count: 4
        memory: 4G
        environment_variables:
        shutdown_vm: false
        sync_files: runner-to-vm
        run: |
          sudo pkg update
          sudo pkg install -y cmake llvm libpcap protobuf
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Check Formatting
      uses: cross-platform-actions/action@v0.30.0
      with:
        operating_system: ${{ matrix.platform.os }}
        architecture: ${{ matrix.platform.arch }}
        version: ${{ matrix.platform.os-version }}
        cpu_count: 4
        memory: 4G
        environment_variables:
        shutdown_vm: false
        sync_files: false
        run: $HOME/.cargo/bin/cargo fmt --all -- --check

    - name: Build
      uses: cross-platform-actions/action@v0.30.0
      with:
        operating_system: ${{ matrix.platform.os }}
        architecture: ${{ matrix.platform.arch }}
        version: ${{ matrix.platform.os-version }}
        cpu_count: 4
        memory: 4G
        environment_variables:
        shutdown_vm: false
        sync_files: false
        run: $HOME/.cargo/bin/cargo build --verbose

    - name: Lint
      uses: cross-platform-actions/action@v0.30.0
      with:
        operating_system: ${{ matrix.platform.os }}
        architecture: ${{ matrix.platform.arch }}
        version: ${{ matrix.platform.os-version }}
        cpu_count: 4
        memory: 4G
        environment_variables:
        shutdown_vm: false
        sync_files: false
        run: $HOME/.cargo/bin/cargo clippy -- -D warnings

    - name: Test
      uses: cross-platform-actions/action@v0.30.0
      with:
        operating_system: ${{ matrix.platform.os }}
        architecture: ${{ matrix.platform.arch }}
        version: ${{ matrix.platform.os-version }}
        cpu_count: 4
        memory: 4G
        environment_variables:
        shutdown_vm: true
        sync_files: false
        run: $HOME/.cargo/bin/cargo test -- --nocapture